.TH "core/src/main/java/com/lobsterchops/accorncollector/AccornManager.java" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/src/main/java/com/lobsterchops/accorncollector/AccornManager.java
.SH SYNOPSIS
.br
.PP
\fRimport com\&.badlogic\&.gdx\&.audio\&.Sound;\fP
.br
\fRimport com\&.badlogic\&.gdx\&.graphics\&.Texture;\fP
.br
\fRimport com\&.badlogic\&.gdx\&.graphics\&.g2d\&.Sprite;\fP
.br
\fRimport com\&.badlogic\&.gdx\&.graphics\&.g2d\&.SpriteBatch;\fP
.br
\fRimport com\&.badlogic\&.gdx\&.math\&.MathUtils;\fP
.br
\fRimport com\&.badlogic\&.gdx\&.math\&.Rectangle;\fP
.br
\fRimport com\&.badlogic\&.gdx\&.utils\&.Array;\fP
.br
\fRimport com\&.badlogic\&.gdx\&.utils\&.viewport\&.FitViewport;\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcom\&.lobsterchops\&.accorncollector\&.AccornManager\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcom\&.lobsterchops\&.accorncollector\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
