.TH "core/src/main/java/com/lobsterchops/accorncollector Directory Reference" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/src/main/java/com/lobsterchops/accorncollector Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBscreens\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAccornManager\&.java\fP"
.br
.ti -1c
.RI "file \fBMain\&.java\fP"
.br
.ti -1c
.RI "file \fBPlayer\&.java\fP"
.br
.in -1c
