.TH "com.lobsterchops.accorncollector.Main" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.lobsterchops.accorncollector.Main
.SH SYNOPSIS
.br
.PP
.PP
Inherits Game\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreate\fP ()"
.br
.ti -1c
.RI "\fBScreenManager\fP \fBgetScreenManager\fP ()"
.br
.ti -1c
.RI "void \fBdispose\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fR\fBcom\&.badlogic\&.gdx\&.ApplicationListener\fP\fP implementation shared by all platforms\&. 
.PP
Definition at line \fB8\fP of file \fBMain\&.java\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.lobsterchops\&.accorncollector\&.Main\&.create ()"

.PP
Definition at line \fB12\fP of file \fBMain\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.Main\&.dispose ()"

.PP
Definition at line \fB22\fP of file \fBMain\&.java\fP\&.
.SS "\fBScreenManager\fP com\&.lobsterchops\&.accorncollector\&.Main\&.getScreenManager ()"

.PP
Definition at line \fB17\fP of file \fBMain\&.java\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
