.TH "com.lobsterchops.accorncollector.screens.ScreenManager.TransitionType" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.lobsterchops.accorncollector.screens.ScreenManager.TransitionType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFADE\fP"
.br
.ti -1c
.RI "\fBSLIDE_LEFT\fP"
.br
.ti -1c
.RI "\fBSLIDE_RIGHT\fP"
.br
.ti -1c
.RI "\fBSLIDE_UP\fP"
.br
.ti -1c
.RI "\fBSLIDE_DOWN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBScreenManager\&.java\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "com\&.lobsterchops\&.accorncollector\&.screens\&.ScreenManager\&.TransitionType\&.FADE"

.PP
Definition at line \fB15\fP of file \fBScreenManager\&.java\fP\&.
.SS "com\&.lobsterchops\&.accorncollector\&.screens\&.ScreenManager\&.TransitionType\&.SLIDE_DOWN"

.PP
Definition at line \fB19\fP of file \fBScreenManager\&.java\fP\&.
.SS "com\&.lobsterchops\&.accorncollector\&.screens\&.ScreenManager\&.TransitionType\&.SLIDE_LEFT"

.PP
Definition at line \fB16\fP of file \fBScreenManager\&.java\fP\&.
.SS "com\&.lobsterchops\&.accorncollector\&.screens\&.ScreenManager\&.TransitionType\&.SLIDE_RIGHT"

.PP
Definition at line \fB17\fP of file \fBScreenManager\&.java\fP\&.
.SS "com\&.lobsterchops\&.accorncollector\&.screens\&.ScreenManager\&.TransitionType\&.SLIDE_UP"

.PP
Definition at line \fB18\fP of file \fBScreenManager\&.java\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
