.TH "com.lobsterchops.accorncollector.screens.MainMenuScreen" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.lobsterchops.accorncollector.screens.MainMenuScreen
.SH SYNOPSIS
.br
.PP
.PP
Inherits Screen\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainMenuScreen\fP (\fBScreenManager\fP screenManager)"
.br
.ti -1c
.RI "void \fBshow\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP (float delta)"
.br
.ti -1c
.RI "void \fBresize\fP (int width, int height)"
.br
.ti -1c
.RI "void \fBpause\fP ()"
.br
.ti -1c
.RI "void \fBresume\fP ()"
.br
.ti -1c
.RI "void \fBhide\fP ()"
.br
.ti -1c
.RI "void \fBdispose\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBMainMenuScreen\&.java\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.lobsterchops\&.accorncollector\&.screens\&.MainMenuScreen\&.MainMenuScreen (\fBScreenManager\fP screenManager)"

.PP
Definition at line \fB31\fP of file \fBMainMenuScreen\&.java\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.MainMenuScreen\&.dispose ()"

.PP
Definition at line \fB167\fP of file \fBMainMenuScreen\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.MainMenuScreen\&.hide ()"

.PP
Definition at line \fB162\fP of file \fBMainMenuScreen\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.MainMenuScreen\&.pause ()"

.PP
Definition at line \fB152\fP of file \fBMainMenuScreen\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.MainMenuScreen\&.render (float delta)"

.PP
Definition at line \fB53\fP of file \fBMainMenuScreen\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.MainMenuScreen\&.resize (int width, int height)"

.PP
Definition at line \fB118\fP of file \fBMainMenuScreen\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.MainMenuScreen\&.resume ()"

.PP
Definition at line \fB157\fP of file \fBMainMenuScreen\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.MainMenuScreen\&.show ()"

.PP
Definition at line \fB45\fP of file \fBMainMenuScreen\&.java\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
