.TH "com.lobsterchops.accorncollector.screens.GameScreen" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.lobsterchops.accorncollector.screens.GameScreen
.SH SYNOPSIS
.br
.PP
.PP
Inherits Screen\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameScreen\fP (\fBScreenManager\fP screenManager)"
.br
.ti -1c
.RI "void \fBshow\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP (float delta)"
.br
.ti -1c
.RI "void \fBresize\fP (int width, int height)"
.br
.ti -1c
.RI "void \fBpause\fP ()"
.br
.ti -1c
.RI "void \fBresume\fP ()"
.br
.ti -1c
.RI "void \fBhide\fP ()"
.br
.ti -1c
.RI "void \fBdispose\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBGameScreen\&.java\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.lobsterchops\&.accorncollector\&.screens\&.GameScreen\&.GameScreen (\fBScreenManager\fP screenManager)"

.PP
Definition at line \fB44\fP of file \fBGameScreen\&.java\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.GameScreen\&.dispose ()"

.PP
Definition at line \fB165\fP of file \fBGameScreen\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.GameScreen\&.hide ()"

.PP
Definition at line \fB160\fP of file \fBGameScreen\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.GameScreen\&.pause ()"

.PP
Definition at line \fB148\fP of file \fBGameScreen\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.GameScreen\&.render (float delta)"

.PP
Definition at line \fB98\fP of file \fBGameScreen\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.GameScreen\&.resize (int width, int height)"

.PP
Definition at line \fB143\fP of file \fBGameScreen\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.GameScreen\&.resume ()"

.PP
Definition at line \fB154\fP of file \fBGameScreen\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.GameScreen\&.show ()"

.PP
Definition at line \fB49\fP of file \fBGameScreen\&.java\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
