.TH "com.lobsterchops.accorncollector.screens.ScreenManager" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.lobsterchops.accorncollector.screens.ScreenManager
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBTransitionType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScreenManager\fP (Game game)"
.br
.ti -1c
.RI "void \fBsetScreen\fP (Screen screen)"
.br
.ti -1c
.RI "void \fBsetScreen\fP (Screen screen, \fBTransitionType\fP transitionType, float duration)"
.br
.ti -1c
.RI "Screen \fBgetCurrentScreen\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBScreenManager\&.java\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.lobsterchops\&.accorncollector\&.screens\&.ScreenManager\&.ScreenManager (Game game)"

.PP
Definition at line \fB27\fP of file \fBScreenManager\&.java\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Screen com\&.lobsterchops\&.accorncollector\&.screens\&.ScreenManager\&.getCurrentScreen ()"

.PP
Definition at line \fB48\fP of file \fBScreenManager\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.ScreenManager\&.setScreen (Screen screen)"

.PP
Definition at line \fB31\fP of file \fBScreenManager\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.screens\&.ScreenManager\&.setScreen (Screen screen, \fBTransitionType\fP transitionType, float duration)"

.PP
Definition at line \fB35\fP of file \fBScreenManager\&.java\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
