.TH "com.lobsterchops.accorncollector.AccornManager" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.lobsterchops.accorncollector.AccornManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccornManager\fP (Texture texture, Sound collectSound)"
.br
.ti -1c
.RI "void \fBcreateAccorn\fP (FitViewport viewport)"
.br
.ti -1c
.RI "void \fBupdate\fP (float delta, FitViewport viewport, Rectangle playerBounds)"
.br
.ti -1c
.RI "void \fBdraw\fP (SpriteBatch batch)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Manages spawning, moving and collisions for acorns\&. 
.PP
Definition at line \fB16\fP of file \fBAccornManager\&.java\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.lobsterchops\&.accorncollector\&.AccornManager\&.AccornManager (Texture texture, Sound collectSound)"

.PP
Definition at line \fB23\fP of file \fBAccornManager\&.java\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.lobsterchops\&.accorncollector\&.AccornManager\&.createAccorn (FitViewport viewport)"

.PP
Definition at line \fB29\fP of file \fBAccornManager\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.AccornManager\&.draw (SpriteBatch batch)"

.PP
Definition at line \fB72\fP of file \fBAccornManager\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.AccornManager\&.update (float delta, FitViewport viewport, Rectangle playerBounds)"

.PP
Definition at line \fB44\fP of file \fBAccornManager\&.java\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
