.TH "com.lobsterchops.accorncollector.Player" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.lobsterchops.accorncollector.Player
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayer\fP (Texture texture, float startX, float startY)"
.br
.ti -1c
.RI "void \fBupdate\fP (float delta, FitViewport viewport)"
.br
.ti -1c
.RI "void \fBdraw\fP (SpriteBatch batch)"
.br
.ti -1c
.RI "Rectangle \fBgetBounds\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Encapsulates the player sprite, input handling and bounds\&. 
.PP
Definition at line \fB16\fP of file \fBPlayer\&.java\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.lobsterchops\&.accorncollector\&.Player\&.Player (Texture texture, float startX, float startY)"

.PP
Definition at line \fB22\fP of file \fBPlayer\&.java\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.lobsterchops\&.accorncollector\&.Player\&.draw (SpriteBatch batch)"

.PP
Definition at line \fB52\fP of file \fBPlayer\&.java\fP\&.
.SS "Rectangle com\&.lobsterchops\&.accorncollector\&.Player\&.getBounds ()"

.PP
Definition at line \fB57\fP of file \fBPlayer\&.java\fP\&.
.SS "void com\&.lobsterchops\&.accorncollector\&.Player\&.update (float delta, FitViewport viewport)"

.PP
Definition at line \fB29\fP of file \fBPlayer\&.java\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
