.TH "core/src/main/java/com/lobsterchops/accorncollector/Main.java" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/src/main/java/com/lobsterchops/accorncollector/Main.java
.SH SYNOPSIS
.br
.PP
\fRimport com\&.badlogic\&.gdx\&.Game;\fP
.br
\fRimport com\&.lobsterchops\&.accorncollector\&.screens\&.MainMenuScreen;\fP
.br
\fRimport com\&.lobsterchops\&.accorncollector\&.screens\&.ScreenManager;\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcom\&.lobsterchops\&.accorncollector\&.Main\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcom\&.lobsterchops\&.accorncollector\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
