.TH "core/src/main/java/com/lobsterchops/accorncollector/screens/ScreenManager.java" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/src/main/java/com/lobsterchops/accorncollector/screens/ScreenManager.java
.SH SYNOPSIS
.br
.PP
\fRimport com\&.badlogic\&.gdx\&.Game;\fP
.br
\fRimport com\&.badlogic\&.gdx\&.Gdx;\fP
.br
\fRimport com\&.badlogic\&.gdx\&.Screen;\fP
.br
\fRimport com\&.badlogic\&.gdx\&.graphics\&.Color;\fP
.br
\fRimport com\&.badlogic\&.gdx\&.graphics\&.GL20;\fP
.br
\fRimport com\&.badlogic\&.gdx\&.graphics\&.g2d\&.SpriteBatch;\fP
.br
\fRimport com\&.badlogic\&.gdx\&.graphics\&.glutils\&.ShapeRenderer;\fP
.br
\fRimport com\&.badlogic\&.gdx\&.math\&.Interpolation;\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcom\&.lobsterchops\&.accorncollector\&.screens\&.ScreenManager\fP"
.br
.ti -1c
.RI "enum \fBcom\&.lobsterchops\&.accorncollector\&.screens\&.ScreenManager\&.TransitionType\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcom\&.lobsterchops\&.accorncollector\&.screens\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
